version: '2'

services:
  php:
    container_name: php-fpm
    image: php:7.1-fpm
    ports: [ "9000:9000" ]
    volumes:
      - ./:/usr/share/nginx/html
    links:
      - arangodb


  arangodb:
    container_name: arangodb
    image: arangodb/arangodb:3.2.1
    restart: on-failure:10
    environment:
      ARANGO_ROOT_PASSWORD: "openSesame"
    ports: [ "8529:8529" ]

  web:
    container_name: nginx
    image: nginx
    volumes:
      - ./vendor:/opt/webapp/vendor
      - ./:/usr/share/nginx/html
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/thedevelchase.com.conf
    ports: [ "8080:80" ]
    restart: on-failure:10
    environment:
      - VIRTUAL_HOST=thedevelchase.com
    links:
      - arangodb
      - php

